name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Esta permissão é ESSENCIAL para poder fazer push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check if public/index.html exists
        run: |
          if [ ! -f public/index.html ]; then
            echo "Arquivo public/index.html não encontrado!"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public